server:
  port: 8090
spring:
  http:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/jeesite?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true



